<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>ScheduleEditor</AssemblyName>
    <Version>1.0.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectCapability Include="Avalonia" />
    <TrimmerRootAssembly Include="Avalonia.Themes.Fluent" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
    <PackageReference Include="Avalonia.ReactiveUI" />
      <PackageReference Include="Avalonia.Controls.DataGrid" />
      <PackageReference Include="Avalonia.Themes.Fluent" />
      <PackageReference Include="Velopack" />      
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\Meadow.CLI\Source\Meadow.HCom\Meadow.HCom.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\Meadow.CLI\Source\Meadow.Tooling.Core\Meadow.Tooling.Core.csproj" />
    <ProjectReference Include="..\..\Driver\Meadow.Foundation.MicroScheduler\Meadow.Foundation.MicroScheduler.csproj" />
  </ItemGroup>
</Project>
